language: java

jdk:
  - oraclejdk8

matrix:
  fast_finish: true

script: "mvn clean install"

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/56a42f65b462c237bbe9
    on_success: change
    on_failure: always
    on_start: false
